language: python
sudo: enabled
services:
    - mysql
python:
    - "3.6"
env:
    global:
     - TRAVIS=true
     - DJANGO_SETTINGS_MODULE="djangoblog.settings"

install:
  - pip install -r requirements.txt

before_script:
    - mysql -e 'CREATE DATABASE `django_east` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;'

script:
    - python manage.py makemigrations
    - python manage.py migrate
