# Generated by Django 2.0.13 on 2019-08-21 06:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='description',
            field=models.CharField(default='一个学习、交流python(django)的个人网站', max_length=200, verbose_name='网站描述'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='keywords',
            field=models.CharField(default='django', max_length=200, verbose_name='关键字'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='sub_title',
            field=models.CharField(default='我的博客', max_length=200, verbose_name='网站副名称'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='title',
            field=models.CharField(default='我的博客', max_length=100, verbose_name='网站主名称'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='arrange_info',
            field=models.CharField(default='Nginx+Gunicorn', max_length=100, verbose_name='部署信息'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='created_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='2019年8月'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='development_info',
            field=models.CharField(default='Python3.6+Django2.0', max_length=100, verbose_name='开发信息'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='record_info',
            field=models.CharField(default='粤ICP备19099198号', max_length=100, verbose_name='备案信息'),
        ),
        migrations.AlterField(
            model_name='social',
            name='github',
            field=models.URLField(default='https://github.com/xrq0663/mysite_pro', verbose_name='Github地址'),
        ),
        migrations.AlterField(
            model_name='social',
            name='qq',
            field=models.CharField(default='1279331881', max_length=20, verbose_name='QQ号码'),
        ),
        migrations.AlterField(
            model_name='social',
            name='wechat',
            field=models.CharField(default='xrq0663', max_length=50, verbose_name='微信'),
        ),
    ]
